import React, { useState } from 'react';
import { FormControl, ListGroup } from 'react-bootstrap';
import { useNavigate } from 'react-router-dom';

const SearchBox = () => {
    const [query, setQuery] = useState('');
    const [suggestions, setSuggestions] = useState([]);
    const navigate = useNavigate();
    const items = [
        "Abacavir / Lamivudine 600mg/300mg",
        "Acyclovir 200mg Capsule",
        "Acyclovir 400mg",
        "Allopurinol 100mg",
        "Allopurinol 300mg",
        "Amiodarone HCl 200mg",
        "Amiodarone HCl 400mg",
        "Amitriptyline 100mg",
        "Amitriptyline 10mg",
        "Amitriptyline 150mg",
        "Amitriptyline 25mg",
        "Amitriptyline 50mg",
        "Amitriptyline 75mg",
        "Amlodipine 10mg",
        "Amlodipine 2.5mg",
        "Amlodipine 5mg",
        "Amlodipine Besy-Benazepril HCl 5-40mg Capsule",
        "Amlodipine Besylate-Benazepril HCl 10mg-20mg",
        "Amlodipine Besylate-Benazepril HCl 10mg-40mg",
        "Amlodipine Besylate-Benazepril HCl 2.5mg-10mg",
        "Amlodipine Besylate-Benazepril HCl 5mg-10mg",
        "Amlodipine Besylate-Benazepril HCl 5mg-20mg",
        "Amlodipine Besylate-Valsartan 10-160mg Tablet",
        "Amlodipine Besylate-Valsartan 10-320mg Tablet",
        "Amlodipine Besylate-Valsartan 5-160mg Tablet",
        "Amlodipine Besylate-Valsartan 5-320mg Tablet",
        "Amoxicillin (Trihydrate) 250mg",
        "Amoxicillin (Trihydrate) 500mg",
        "Amoxicillin (Trihydrate) 875mg",
        "Amoxicillin / Clavulanate 875/125mg",
        "Amoxicillin & Clavulanate 250mg-125mg",
        "Amoxicillin & Clavulanate 500-125mg",
        "Amoxicillin 500mg Capsule",
        "Aspirin 81mg Tablet Chewable",
        "Atenolol 100mg",
        "Atenolol 25mg",
        "Atenolol 50mg",
        "Atorvastatin 10mg",
        "Atorvastatin 20mg",
        "Atorvastatin 40mg",
        "Atorvastatin 80mg",
        "Azithromycin 250mg",
        "Azithromycin 500mg",
        "Azithromycin 600mg",
        "B-Complex W/C & Folic Acid 1mg Capsule",
        "Baclofen 10mg",
        "Baclofen 20mg",
        "Baclofen 5mg",
        "Benazepril HCl 10mg",
        "Benazepril HCl 20mg",
        "Benazepril HCl 40mg",
        "Benazepril HCl 5mg",
        "Benazepril-Hydrochlorothiazide 10-12.5mg Tablet",
        "Benazepril-Hydrochlorothiazide 20-12.5mg Tablet",
        "Benazepril-Hydrochlorothiazide 20-25mg Tablet",
        "Benazepril-Hydrochlorothiazide 5-6.25mg Tablet",
        "Benzonatate 100mg",
        "Benzonatate 200mg",
        "Benztropine Mesylate 1mg",
        "Benztropine Mesylate 2mg",
        "Bisoprolol Fumarate 10mg",
        "Bisoprolol Fumarate 5mg",
        "Bumetanide 0.5mg",
        "Bumetanide 1mg",
        "Bumetanide 2mg Tablet",
        "Bupropion HCl 100mg",
        "Bupropion HCl 75mg",
        "Bupropion HCl ER (Smoking Det) 150mg Tablet Extended Release",
        "Bupropion SR 100mg",
        "Bupropion SR 200mg",
        "Bupropion SR150mg",
        "Bupropion XL 150mg",
        "Bupropion XL 300mg",
        "Buspirone HCL 10mg",
        "Buspirone HCL 15mg",
        "Buspirone HCl 30mg",
        "Buspirone HCL 5mg",
        "Buspirone HCl 7.5mg",
        "Candesartan Cilexetil 16mg Tablet",
        "Candesartan Cilexetil 32mg Tablet",
        "Candesartan Cilexetil 4mg Tablet",
        "Candesartan Cilexetil 8mg Tablet",
        "Candesartan Cilexetil-HCTZ 16-12.5mg Tablet",
        "Candesartan Cilexetil-HCTZ 32-12.5mg Tablet",
        "Candesartan Cilexetil-HCTZ 32-25mg Tablet",
        "Captopril 100mg Tablet",
        "Captopril 12.5mg Tablet",
        "Captopril 25mg Tablet",
        "Captopril 50mg Tablet",
        "Captopril-Hydrochlorothiazide 25-15mg Tablet",
        "Captopril-Hydrochlorothiazide 25-25mg Tablet",
        "Captopril-Hydrochlorothiazide 50-15mg Tablet",
        "Captopril-Hydrochlorothiazide 50-25mg Tablet",
        "Carbamazepine ER 100mg Tablet Extended Release",
        "Carbamazepine ER 200mg Tablet Extended Release",
        "Carbamazepine ER 400mg Tablet Extended Release",
        "Carbidopa & Levodopa 10mg-100mg",
        "Carbidopa & Levodopa 25/100mg",
        "Carvedilol 12.5mg",
        "Carvedilol 25mg",
        "Carvedilol 3.125mg",
        "Carvedilol 6.25mg",
        "Cefdinir 300mg",
        "Celecoxib 100mg",
        "Celecoxib 200mg",
        "Cephalexin 250mg",
        "Cephalexin 500mg",
        "Cephalexin Suspension 125mg/5mL",
        "Cetirizine 10mg",
        "Cetirizine HCl 5mg",
        "Chlorthalidone 25mg",
        "Chlorthalidone 50mg",
        "Ciprofloxacin 250mg",
        "Ciprofloxacin 500mg",
        "Ciprofloxacin 750mg",
        "Citalopram Hydrobromide 10mg",
        "Citalopram Hydrobromide 20mg",
        "Citalopram Hydrobromide 40mg",
        "Clindamycin HCL 300mg",
        "Clonidine 0.1mg",
        "Clonidine 0.2mg",
        "Clonidine 0.3mg",
        "Clopidogrel 75mg",
        "Colchicine 0.6mg",
        "Cyclobenzaprine 10mg",
        "Cyclobenzaprine 5mg",
        "Cyclobenzaprine 7.5mg",
        "Darunavir 600mg Tablet",
        "Desvenlafaxine Succinate Extended Release (ER) 100mg",
        "Desvenlafaxine Succinate Extended Release (ER) 24HR 25mg (Base Equiv)",
        "Desvenlafaxine Succinate Extended Release (ER) 50mg",
        "Dexamethasone 2mg Tablet",
        "Dexamethasone 4mg",
        "Dexamethasone 6mg Tablet",
        "Diclofenac Sodium ER 75mg",
        "Dicyclomine 20mg",
        "Dicyclomine HCl 10mg",
        "Digoxin 125mcg",
        "Digoxin 62.5mcg Tablet",
        "Diltiazem HCl 120mg Tablet",
        "Diltiazem HCl 30mg Tablet",
        "Diltiazem HCl 60mg Tablet",
        "Diltiazem HCl 90mg Tablet",
        "Diltiazem HCl ER 60mg Capsule Extended Release",
        "Diltiazem HCl ER 90mg Capsule Extended Release",
        "Diltiazem HCl Extended Release 120mg Capsule Extended Release",
        "Diltiazem HCl Extended Release 180mg Capsule Extended Release",
        "Diltiazem HCl Extended Release 240mg Capsule Extended Release",
        "Diltiazem HCl Extended Release 360mg Capsule Extended Release",
        "Divalproex Sodium Delayed Release (DR) 125mg",
        "Divalproex Sodium Delayed Release (DR) 250mg",
        "Divalproex Sodium Delayed Release (DR) 500mg",
        "Divalproex Sodium ER 250mg",
        "Divalproex Sodium ER 500mg",
        "Docusate Sodium 100mg",
        "Docusate Sodium 50mg",
        "Doxycycline 100mg",
        "Doxycycline 20mg",
        "Doxycycline 50mg",
        "Duloxetine DR 20mg Capsule",
        "Duloxetine DR 30mg Capsule",
        "Duloxetine DR 40mg Capsule",
        "Duloxetine DR 60mg Capsule",
        "Efavirenz / Emtricitabine / Tenofovir 600mg/200mg/300mg",
        "Empagliflozin 10mg",
        "Empagliflozin 25mg",
        "Empagliflozin 5mg",
        "Empagliflozin Linagliptin 10mg-5mg Tablet",
        "Empagliflozin Linagliptin 25mg-5mg Tablet",
        "Emtricitabine / Tenofovir 200mg/300mg",
        "Enalapril Maleate 10mg",
        "Enalapril Maleate 2.5mg",
        "Enalapril Maleate 20mg",
        "Enalapril Maleate 5mg",
        "Escitalopram Oxalate 10mg",
        "Escitalopram Oxalate 20mg",
        "Escitalopram Oxalate 5mg",
        "Esomeprazole 20mg",
        "Esomeprazole 40mg",
        "Eszopiclone 1mg",
        "Eszopiclone 2mg",
        "Eszopiclone 3mg",
        "Ezetimibe 10mg",
        "Famotidine 10mg",
        "Famotidine 20mg",
        "Famotidine 40mg",
        "Fenofibrate 145mg",
        "Fenofibrate 48mg",
        "Fenofibrate DR 160mg",
        "Fluconazole 100mg",
        "Fluconazole 150mg",
        "Fluconazole 200mg",
        "Fluoxetine HCl 10mg",
        "Fluoxetine HCl 20mg",
        "Fluoxetine HCl 40mg",
        "Fluoxetine HCl 60mg",
        "Fluoxetine HCl 90mg",
        "Fluoxetine HCl 90mg DR",
        "Fluoxetine HCl Oral Solution 20mg/5mL",
        "Fluticasone Nasal Spray 50mcg",
        "Fluticasone Propionate 50mcg",
        "Folic Acid 1mg",
        "Folic Acid 5mg",
        "Furosemide 20mg",
        "Furosemide 40mg",
        "Furosemide 80mg",
        "Gabapentin 100mg",
        "Gabapentin 300mg",
        "Gabapentin 400mg",
        "Gabapentin 600mg",
        "Gabapentin 800mg",
        "Glimepiride 1mg",
        "Glimepiride 2mg",
        "Glimepiride 4mg",
        "Glipizide 10mg",
        "Glipizide 2.5mg",
        "Glipizide 5mg",
        "Glipizide ER 10mg",
        "Glipizide ER 2.5mg",
        "Glipizide ER 5mg",
        "Glipizide XL 10mg",
        "Glipizide XL 5mg",
        "Glucagon 1mg",
        "Glyburide 1.25mg",
        "Glyburide 2.5mg",
        "Glyburide 5mg",
        "Hydrochlorothiazide 12.5mg",
        "Hydrochlorothiazide 25mg",
        "Hydrochlorothiazide 50mg",
        "Hydrocodone Bitartrate-Acetaminophen 10-325mg Tablet",
        "Hydrocodone Bitartrate-Acetaminophen 10-500mg Tablet",
        "Hydrocodone Bitartrate-Acetaminophen 10-650mg Tablet",
        "Hydrocodone Bitartrate-Acetaminophen 5-325mg Tablet",
        "Hydrocodone Bitartrate-Acetaminophen 7.5-325mg Tablet",
        "Hydrocodone Bitartrate-Acetaminophen 7.5-500mg Tablet",
        "Hydrocodone Bitartrate-Acetaminophen 7.5-650mg Tablet",
        "Hydrocodone Bitartrate-Acetaminophen 7.5-750mg Tablet",
        "Hydroxychloroquine 200mg Tablet",
        "Hydroxyzine HCl 10mg",
        "Hydroxyzine HCl 25mg",
        "Hydroxyzine HCl 50mg",
        "Ibuprofen 400mg",
        "Ibuprofen 600mg",
        "Ibuprofen 800mg",
        "Indomethacin 25mg",
        "Indomethacin 50mg",
        "Irbesartan 150mg",
        "Irbesartan 300mg",
        "Isosorbide Dinitrate 10mg",
        "Isosorbide Dinitrate 2.5mg",
        "Isosorbide Dinitrate 30mg",
        "Isosorbide Dinitrate 40mg",
        "Isosorbide Dinitrate 5mg",
        "Isosorbide Mononitrate 10mg",
        "Isosorbide Mononitrate 20mg",
        "Isosorbide Mononitrate 30mg",
        "Isosorbide Mononitrate 60mg",
        "Lamivudine / Tenofovir 300mg/300mg",
        "Lamotrigine 100mg",
        "Lamotrigine 150mg",
        "Lamotrigine 25mg",
        "Lamotrigine 50mg",
        "Lamotrigine 5mg",
        "Lamotrigine 75mg",
        "Lamotrigine Dispersible 2mg",
        "Lamotrigine Dispersible 5mg",
        "Lansoprazole 15mg",
        "Lansoprazole 30mg",
        "Latanoprost 0.005% Eye Drops",
        "Levetiracetam 1000mg Tablet",
        "Levetiracetam 250mg Tablet",
        "Levetiracetam 500mg Tablet",
        "Levetiracetam 750mg Tablet",
        "Levofloxacin 250mg",
        "Levofloxacin 500mg",
        "Levofloxacin 750mg",
        "Levothyroxine 0.025mg",
        "Levothyroxine 0.05mg",
        "Levothyroxine 0.075mg",
        "Levothyroxine 0.1mg",
        "Levothyroxine 0.125mg",
        "Levothyroxine 0.137mg",
        "Levothyroxine 0.15mg",
        "Levothyroxine 0.175mg",
        "Levothyroxine 0.2mg",
        "Levothyroxine 0.3mg",
        "Levothyroxine Sodium 25mcg",
        "Levothyroxine Sodium 50mcg",
        "Levothyroxine Sodium 75mcg",
        "Levothyroxine Sodium 88mcg",
        "Lisinopril 10mg",
        "Lisinopril 20mg",
        "Lisinopril 30mg",
        "Lisinopril 40mg",
        "Lisinopril 5mg",
        "Lisinopril-HCTZ 10-12.5mg",
        "Lisinopril-HCTZ 20-12.5mg",
        "Lisinopril-HCTZ 20-25mg",
        "Lithium Carbonate 150mg",
        "Lithium Carbonate 300mg",
        "Lithium Carbonate 600mg",
        "Loperamide 2mg",
        "Losartan Potassium 100mg",
        "Losartan Potassium 25mg",
        "Losartan Potassium 50mg",
        "Losartan Potassium HCTZ 100mg-12.5mg",
        "Losartan Potassium HCTZ 100mg-25mg",
        "Losartan Potassium HCTZ 50mg-12.5mg",
        "Lovastatin 10mg",
        "Lovastatin 20mg",
        "Lovastatin 40mg",
        "Magnesium Sulfate 50%",
        "Magnesium Sulfate Paste",
        "Mebendazole 100mg",
        "Medroxyprogesterone 10mg",
        "Meloxicam 10mg",
        "Meloxicam 15mg",
        "Meloxicam 7.5mg",
        "Metformin 1000mg",
        "Metformin 500mg",
        "Metformin 850mg",
        "Metformin HCl ER 500mg Tablet Extended Release",
        "Metformin HCl ER 750mg Tablet Extended Release",
        "Metformin HCl ER 1000mg Tablet Extended Release",
        "Methimazole 10mg",
        "Methimazole 5mg",
        "Methotrexate 10mg",
        "Methotrexate 2.5mg",
        "Methyldopa 125mg",
        "Methyldopa 250mg",
        "Methyldopa 500mg",
        "Methylergonovine 0.2mg",
        "Metoclopramide 10mg",
        "Metoclopramide 5mg",
        "Metoprolol Succinate 100mg",
        "Metoprolol Succinate 200mg",
        "Metoprolol Succinate 25mg",
        "Metoprolol Succinate 50mg",
        "Metoprolol Tartrate 100mg",
        "Metoprolol Tartrate 25mg",
        "Metoprolol Tartrate 50mg",
        "Metoprolol Tartrate 75mg",
        "Metronidazole 250mg",
        "Metronidazole 500mg",
        "Miconazole 2%",
        "Minocycline 100mg",
        "Minocycline 50mg",
        "Minocycline 75mg",
        "Minoxidil 2.5mg",
        "Minoxidil 5mg",
        "Mirtazapine 15mg",
        "Mirtazapine 30mg",
        "Mirtazapine 45mg",
        "Mirtazapine 7.5mg",
        "Montelukast 10mg",
        "Montelukast 4mg",
        "Montelukast 5mg",
        "Morphine Sulfate 15mg",
        "Morphine Sulfate 30mg",
        "Morphine Sulfate 60mg",
        "Morphine Sulfate 100mg",
        "Naproxen 250mg",
        "Naproxen 500mg",
        "Naproxen Sodium 275mg",
        "Naproxen Sodium 550mg",
        "Nevirapine 200mg",
        "Nifedipine 10mg",
        "Nifedipine 20mg",
        "Nifedipine ER 30mg",
        "Nifedipine ER 60mg",
        "Nifedipine ER 90mg",
        "Nitrofurantoin 100mg",
        "Nitrofurantoin 50mg",
        "Nitrofurantoin 75mg",
        "Nitroglycerin 0.3mg",
        "Nitroglycerin 0.6mg",
        "Nitroglycerin 2.5mg",
        "Nitroglycerin 6.5mg",
        "Norethindrone 0.35mg",
        "Nystatin Cream 100,000unit/g",
        "Nystatin Oral Suspension 100,000unit/mL",
        "Nystatin Powder",
        "Nystatin Vaginal Tablet 100,000unit",
        "Ofloxacin 0.3% Eye Drop",
        "Olanzapine 10mg",
        "Olanzapine 15mg",
        "Olanzapine 20mg",
        "Olanzapine 5mg",
        "Olmesartan 20mg",
        "Olmesartan 40mg",
        "Olmesartan 5mg",
        "Olmesartan-Amlodipine 40mg/5mg",
        "Olmesartan-HCTZ 20mg-12.5mg",
        "Olmesartan-HCTZ 40mg-25mg",
        "Omeprazole 10mg",
        "Omeprazole 20mg",
        "Omeprazole 40mg",
        "Ondansetron 4mg",
        "Ondansetron 8mg",
        "Oseltamivir 30mg",
        "Oseltamivir 45mg",
        "Oseltamivir 75mg",
        "Oxcarbazepine 150mg",
        "Oxcarbazepine 300mg",
        "Oxcarbazepine 600mg",
        "Oxybutynin 5mg",
        "Oxybutynin 2.5mg",
        "Pantoprazole 20mg",
        "Pantoprazole 40mg",
        "Paroxetine HCl 10mg",
        "Paroxetine HCl 20mg",
        "Paroxetine HCl 30mg",
        "Paroxetine HCl 40mg",
        "Paroxetine HCl 7.5mg",
        "Penicillin V 250mg",
        "Penicillin V 500mg",
        "Phenobarbital 100mg",
        "Phenobarbital 15mg",
        "Phenobarbital 30mg",
        "Phenobarbital 60mg",
        "Phenytoin 100mg",
        "Phenytoin 30mg",
        "Phenytoin 50mg",
        "Phenytoin 200mg",
        "Pioglitazone 15mg",
        "Pioglitazone 30mg",
        "Pioglitazone 45mg",
        "Piroxicam 20mg",
        "Polymyxin B Sulfate-Bacitracin Zinc Eye Ointment 1% / 500 IU",
        "Polymyxin B Sulfate-TMP Eye Drop 10,000units/mL-1mg/mL",
        "Potassium Chloride 10%",
        "Potassium Chloride 20%",
        "Potassium Chloride 8%",
        "Pramipexole 0.25mg",
        "Pramipexole 0.5mg",
        "Pramipexole 1mg",
        "Pramipexole 1.5mg",
        "Pravastatin 10mg",
        "Pravastatin 20mg",
        "Pravastatin 40mg",
        "Pravastatin 80mg",
        "Prednisolone 15mg",
        "Prednisolone 5mg",
        "Prednisone 1mg",
        "Prednisone 2.5mg",
        "Prednisone 20mg",
        "Prednisone 5mg",
        "Pregabalin 150mg",
        "Pregabalin 25mg",
        "Pregabalin 300mg",
        "Pregabalin 50mg",
        "Pregabalin 75mg",
        "Progesterone 100mg",
        "Progesterone 200mg",
        "Promethazine 25mg",
        "Promethazine 50mg",
        "Propylthiouracil 50mg",
        "Quetiapine 100mg",
        "Quetiapine 200mg",
        "Quetiapine 300mg",
        "Quetiapine 400mg",
        "Quetiapine 25mg",
        "Quetiapine 50mg",
        "Quetiapine 800mg",
        "Rabeprazole 10mg",
        "Rabeprazole 20mg",
        "Ramipril 10mg",
        "Ramipril 2.5mg",
        "Ramipril 5mg",
        "Ranitidine 150mg",
        "Ranitidine 300mg",
        "Rifampicin 150mg",
        "Rifampicin 300mg",
        "Risperidone 1mg",
        "Risperidone 2mg",
        "Risperidone 3mg",
        "Risperidone 4mg",
        "Risperidone 6mg",
        "Rosuvastatin 10mg",
        "Rosuvastatin 20mg",
        "Rosuvastatin 40mg",
        "Rosuvastatin 5mg",
        "Salbutamol 2mg",
        "Salbutamol 4mg",
        "Salbutamol Inhaler 100mcg",
        "Salbutamol Inhaler 200mcg",
        "Sertraline 100mg",
        "Sertraline 25mg",
        "Sertraline 50mg",
        "Sildenafil 100mg",
        "Sildenafil 50mg",
        "Simvastatin 10mg",
        "Simvastatin 20mg",
        "Simvastatin 40mg",
        "Simvastatin 80mg",
        "Sitagliptin 100mg",
        "Sitagliptin 25mg",
        "Sitagliptin 50mg",
        "Spironolactone 100mg",
        "Spironolactone 25mg",
        "Spironolactone 50mg",
        "Sulfamethoxazole / Trimethoprim 200mg/40mg",
        "Sulfamethoxazole / Trimethoprim 400mg/80mg",
        "Sulfamethoxazole / Trimethoprim 800mg/160mg",
        "Sumatriptan 100mg",
        "Sumatriptan 50mg",
        "Tamsulosin 0.4mg",
        "Tenofovir 300mg",
        "Terazosin 1mg",
        "Terazosin 2mg",
        "Terazosin 5mg",
        "Terazosin 10mg",
        "Tetracycline 250mg",
        "Tetracycline 500mg",
        "Thiamine HCl 100mg",
        "Thiamine HCl 50mg",
        "Thyroxine 50mg",
        "Thyroxine 100mg",
        "Thyroxine 200mg",
        "Thyroxine 25mg",
        "Tizanidine 2mg",
        "Tizanidine 4mg",
        "Topiramate 100mg",
        "Topiramate 200mg",
        "Topiramate 25mg",
        "Topiramate 50mg",
        "Tramadol 100mg",
        "Tramadol 150mg",
        "Tramadol 200mg",
        "Tramadol 300mg",
        "Tramadol 50mg",
        "Tretinoin Cream 0.025%",
        "Tretinoin Cream 0.05%",
        "Tretinoin Cream 0.1%",
        "Triamcinolone Acetonide Cream 0.025%",
        "Triamcinolone Acetonide Cream 0.1%",
        "Triamcinolone Acetonide Ointment 0.1%",
        "Triamcinolone Acetonide 40mg",
        "Triamterene-HCTZ 37.5mg-25mg",
        "Triamterene-HCTZ 75mg-50mg",
        "Trimethoprim 100mg",
        "Trimethoprim 200mg",
        "Valacyclovir 1,000mg",
        "Valacyclovir 500mg",
        "Valproic Acid 250mg",
        "Valproic Acid 500mg",
        "Valsartan 160mg",
        "Valsartan 40mg",
        "Valsartan 80mg",
        "Vancomycin 125mg",
        "Vancomycin 250mg",
        "Vancomycin 500mg",
        "Vardenafil 10mg",
        "Vardenafil 20mg",
        "Vildagliptin 50mg",
        "Vitamin A Capsules 200,000 IU",
        "Vitamin B Complex Tablets",
        "Vitamin B Complex Syrup",
        "Vitamin B1 + B6 + B12",
        "Vitamin B12 Injection 100mcg/mL",
        "Vitamin B12 Injection 1,000mcg/mL",
        "Vitamin B12 Injection 200mcg/mL",
        "Vitamin B2 50mg",
        "Vitamin B2 100mg",
        "Vitamin C 100mg",
        "Vitamin C 500mg",
        "Vitamin D3 100,000 IU",
        "Vitamin D3 1,000 IU",
        "Vitamin D3 400 IU",
        "Vitamin D3 50,000 IU",
        "Vitamin E 100mg",
        "Vitamin E 200mg",
        "Vitamin E 400mg",
        "Warfarin 1mg",
        "Warfarin 2.5mg",
        "Warfarin 2mg",
        "Warfarin 3mg",
        "Warfarin 5mg",
        "Warfarin 10mg",
        "Zidovudine 100mg",
        "Zidovudine 300mg",
        "Zinc Sulfate 110mg",
        "Zinc Sulfate 20mg",
        "Zinc Sulfate 27.5mg",
        "Zinc Sulfate 55mg",
        "Zonisamide 100mg",
        "Zonisamide 25mg",
        "Zonisamide 50mg"
    ]



const handleInputChange = (e) => {
        const value = e.target.value;
        setQuery(value);
        if (value) {
            const filteredSuggestions = items.filter(item =>
                item.toLowerCase().includes(value.toLowerCase())
            );
            setSuggestions(filteredSuggestions);
        } else {
            setSuggestions([]);
        }
    };

    const handleSuggestionClick = (suggestion) => {
        setQuery(suggestion);
        setSuggestions([]);
        navigate(`/medicineDetails/${suggestion}`);
    };

    return (
        <div className="search-box ">
            <FormControl
                type="text"
                placeholder="Search by brand name, generic name, or by health condition..."
                value={query}
                onChange={handleInputChange}
                style={{ padding:15 }}
            />
            {suggestions.length > 0 && (
                <ListGroup className="autocomplete-dropdown">
                    {suggestions.map((suggestion, index) => (
                        <ListGroup.Item
                            key={index}
                            onClick={() => handleSuggestionClick(suggestion)}
                        >
                            {suggestion}
                        </ListGroup.Item>
                    ))}
                </ListGroup>
            )}
        </div>
    );
};

export default SearchBox;
